httpswwwhemfridse/Controllers/SearchController.cs
using httpswwwhemfridse.Models; 
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace httpswwwhemfridse.Controllers
{
    public class SearchController : Controller
    {
        // GET: SearchController
        public ActionResult Index()
        {
            return View("Views/Search.cshtml");
        }

        [HttpPost]
        public ActionResult Index(SearchModel search)
        {
            string searchWord = search.searchWord;
            return View("Views/Search.cshtml");
        }

        // GET: SearchController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SearchController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SearchController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SearchController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SearchController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SearchController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

httpswwwhemfridse/Views/Search.cshtml
@model httpswwwhemfridse.Models.SearchModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
</head>
<body>
    @using (Html.BeginForm("Index", "Search", FormMethod.Post))
    {
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th colspan="2" align="center">Person Details</th>
            </tr>
            <tr>
                <td>PersonId: </td>
                <td>
                    @Html.TextBoxFor(m => m.searchWord)
                </td>
            </tr>
            @*<tr>
                <td>Name: </td>
                <td>
                    @Html.TextBoxFor(m => m.Name)
                </td>
            </tr>
            <tr>
                <td>Gender: </td>
                <td>
                    @Html.DropDownListFor(m => m.Gender, new List<SelectListItem>
                   { new SelectListItem{Text="Male", Value="M"},
                     new SelectListItem{Text="Female", Value="F"}}, "Please select")
                </td>
            </tr>
            <tr>
                <td>City: </td>
                <td>
                    @Html.TextBoxFor(m => m.City)
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" /></td>
            </tr>*@
        </table>
    }
</body>
</html>

httpswwwhemfridse/Views/SearchResult.cshtml
@model httpswwwhemfridse.Models.SearchModel
@* 10.9.2022. I request to access ""pricerunner.se"" price comparison sites api because
    according to https://www.design.pricerunner.com/merchant-api
    "Before you can start to access our Merchant API you need to get a token from us."
    I decide, so long, create a sql database to this project
    with help of this website: https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/getting-started-with-mvc/getting-started-with-mvc-part4
    So in visual studio server explorer I right click
    on data connections and choose "Add connection"but I get error
    The Data Source value in the connection string specifies an instance of SQL Server that is not installed""
    I commit and push with message "10.9.2022. Adding database to project"*@

@* 15.9.2022. On a new computer I commit to Git Changes with message "15.9.2022. Commit all to Git
        Changes from a new computer when I push I to Git Changes I get error: Opening repositories:
    C:\Users\Attila\Desktop\httpswwwpandycocampaignflyttform
    Commit 11ea8a24 created locally in repository C:\Users\Attila\Desktop\httpswwwpandycocampaignflyttform
    Pushing master
    Remote: Invalid username or password.
    Error encountered while pushing to the remote repository: Git failed with a fatal error.
    Git failed with a fatal error.
    Authentication failed for 'https://github.com/AttilaStarkenius/httpswwwpandycocampaignflyttform.git/'
    Pushing to https://github.com/AttilaStarkenius/httpswwwpandycocampaignflyttform.git

    Failed to push to the remote repository. See the Output window for more details.
*@

@* 16.9.2022. I try to fix the push fail "Opening repositories:
    C:\Users\Attila\Desktop\httpswwwpandycocampaignflyttform
    Commit 11ea8a24 created locally in repository C:\Users\Attila\Desktop\httpswwwpandycocampaignflyttform
    Pushing master
    Remote: Invalid username or password.
    Error encountered while pushing to the remote repository: Git failed with a fatal error.
    Git failed with a fatal error.
    Authentication failed for 'https://github.com/AttilaStarkenius/httpswwwpandycocampaignflyttform.git/'
    Pushing to https://github.com/AttilaStarkenius/httpswwwpandycocampaignflyttform.git

    Failed to push to the remote repository. See the Output window for more details."
    by moving the project to source\repos map - earlier it was in \desktop map. I use simple
    commit message "16.9.2022. moving project from desktop to repos map, trying to fix fatal git error"
    and not until now github sign in web page https://github.com/login?client_id=0120e057bd645470c1ed&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3D0120e057bd645470c1ed%26code_challenge%3DjRTWRTFCQ3uxVI0L-yYDa6cISG0Q0eKtvRvVJVVUOWM%26code_challenge_method%3DS256%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A49708%252F%26response_type%3Dcode%26scope%3Drepo%2Bgist%2Bworkflow%26state%3D5cf0ce44a2ca477fa102b520c5f57fb4
    pop up - I wasn't signed in github*@

@* 17.9.2022. I really want to do a cloth combination search page in MVC
    so I use this web page as tutorial: https://www.c-sharpcorner.com/UploadFile/85ed7a/searching-and-paging-in-mvc/
    There is instruction "Create a table in the database with the name Employee.""
    First there has to be a database, so I name it ClothCombinationPriceEstimation and the table Cloth because
    I think it is more suitable in searching clothes scenario. I try to
    start sql server management studio but can't find it, I can't find the SSMS.exe file
    and it leads me to install Sql Server Management studio: https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16
*@

@* 17.9.2022. I also look at https://javascript.plainenglish.io/its-2022-please-don-t-just-use-console-log-anymore-217638337c7d
    and try to use Console.Log Javascript method
    to demonstrate what I think a "Products" table for clothes looks like and
    I use this website: https://www.access-diva.com/dm8.html
    as an example so console.log({ ProductID, pItemID, pStyleID, pPrice, pDescription })
    I commit and push with message "17.9.2022. Testing console.log javascript method"
*@

<script>
    console.log({ ProductID, pItemID, pStyleID, pPrice, pDescription })
</script>


@* 18.9.2022. I get this error when I try to run Microsoft SQL Server Management Studio:

        The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
    like explained on this website: https://stackoverflow.com/questions/61630911/microsoft-sql-server-management-studio-error-at-startup *@

@* 18.9.2022. The issue with fail to start sql server management studio
    leads me to seek another solution like local database with help of this tutorial:
    https://learn.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2022
    I add project-> new item and notice that I really am missing
    the parts needed to do the tutorial, quoting the tutorial itself:
    "To complete this walkthrough, you'll need the .NET desktop development
    and Data storage and processing workloads installed
    in Visual Studio. To install them,
    open Visual Studio Installer and choose Modify (or More > Modify)
    next to the version of Visual Studio you want to modify."
    so that's what I do.
    Actually only Data storage and processing workloads
    were missing so I install those*@

@* 20.9.2022. I follow tutorial https://learn.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2022
    so I want to add to project Service-based Database which I want to name ClothCombinationPriceEstimationDatabase
    but there is no Service based database item option, so I use this tutorial instead:
    https://www.youtube.com/watch?v=R2wbqOFdvUE&ab_channel=ProgrammingProfessor
    I open Edit -> SQL Server object explorer -> SQL Server
    -> (localdb)\MSSQLLocalDB -> Databases
    Which I right click and choose
    "Add New Database" and name it "ClothCombinationPriceEstimation"
    then I commit and push to git changes with
    message "20.9.2022. Adding local database ClothCombinationPriceEstimation"*@

@* 21.9.2022. I use
        https://www.access-diva.com/dm8.html
        as example like I
        mentioned earlies and The local database ClothCombinationPriceEstimation
        is now created in (localdb)\MSSQLLocalDB
        and I go to Tables -> Add new table "tblProducts"
        whose T-SQL first looks like this(I haven't named
        the table to tblProducts yet): "CREATE TABLE [dbo].[Table]
    (
        [Id] INT NOT NULL PRIMARY KEY
    )"
    Also I use this website as a tutorial
    like I have mentioned earlier:
    https://www.youtube.com/watch?v=R2wbqOFdvUE&ab_channel=ProgrammingProfessor
    There is by default "Id" that is "int" and
    doest not allow null values. I rename it to "pProductID"
    and save the table as tblProducts but nothing really
    happens until I click "Update(database)",
I commit and push to git changes with message
    "21.9.2022. creating a
    local database table in the local
    database ClothCombinationPriceEstimation"
*@

@* 21.9.2022. I move working to Index.cshtml to make it easier
    to see changes every time I debug*@